# coding: utf-8

"""
    Impinj Reader Configuration REST API

    This API provides an interface for configuring RFID operations and reporting streams on Impinj Readers as well as updating Impinj Reader firmware and configuring system settings.  When retrieved from a reader, this OpenAPI Document is dynamically updated based on the capabilities of the reader. See the '/openapi.json' path.   # noqa: E501

    OpenAPI spec version: 1.7.0
    Contact: developer-feedback@impinj.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_data_stream_get(self):
        """Test case for data_stream_get

        Get HTTP stream  # noqa: E501
        """
        pass

    def test_device_gpos_get(self):
        """Test case for device_gpos_get

        Retrieve GPO configurations.  # noqa: E501
        """
        pass

    def test_device_gpos_put(self):
        """Test case for device_gpos_put

        Update GPO configurations.  # noqa: E501
        """
        pass

    def test_http_stream_get(self):
        """Test case for http_stream_get

        Retrieve HTTP stream settings  # noqa: E501
        """
        pass

    def test_http_stream_put(self):
        """Test case for http_stream_put

        Update HTTP stream settings  # noqa: E501
        """
        pass

    def test_kafka_get(self):
        """Test case for kafka_get

        Retrieve Kafka settings  # noqa: E501
        """
        pass

    def test_kafka_put(self):
        """Test case for kafka_put

        Update Kafka settings  # noqa: E501
        """
        pass

    def test_mqtt_get(self):
        """Test case for mqtt_get

        Retrieve MQTT settings  # noqa: E501
        """
        pass

    def test_mqtt_put(self):
        """Test case for mqtt_put

        Update MQTT settings  # noqa: E501
        """
        pass

    def test_openapi_json_get(self):
        """Test case for openapi_json_get

        Get OpenAPI Document  # noqa: E501
        """
        pass

    def test_profiles_get(self):
        """Test case for profiles_get

        Retrieve profiles  # noqa: E501
        """
        pass

    def test_profiles_inventory_presets_get(self):
        """Test case for profiles_inventory_presets_get

        Retrieve inventory presets  # noqa: E501
        """
        pass

    def test_profiles_inventory_presets_preset_id_delete(self):
        """Test case for profiles_inventory_presets_preset_id_delete

        Delete inventory preset  # noqa: E501
        """
        pass

    def test_profiles_inventory_presets_preset_id_get(self):
        """Test case for profiles_inventory_presets_preset_id_get

        Retrieve inventory preset detail  # noqa: E501
        """
        pass

    def test_profiles_inventory_presets_preset_id_put(self):
        """Test case for profiles_inventory_presets_preset_id_put

        Create or replace inventory preset  # noqa: E501
        """
        pass

    def test_profiles_inventory_presets_preset_id_start_post(self):
        """Test case for profiles_inventory_presets_preset_id_start_post

        Start inventory preset  # noqa: E501
        """
        pass

    def test_profiles_inventory_presets_schema_get(self):
        """Test case for profiles_inventory_presets_schema_get

        Retrieve inventory schema  # noqa: E501
        """
        pass

    def test_profiles_inventory_start_post(self):
        """Test case for profiles_inventory_start_post

        Start transient inventory preset  # noqa: E501
        """
        pass

    def test_profiles_inventory_tag_get(self):
        """Test case for profiles_inventory_tag_get

        Checks for the presence of a tag in the field of view of an antenna.  # noqa: E501
        """
        pass

    def test_profiles_stop_post(self):
        """Test case for profiles_stop_post

        Stop preset  # noqa: E501
        """
        pass

    def test_status_get(self):
        """Test case for status_get

        Retrieve status  # noqa: E501
        """
        pass

    def test_system_access_authentication_get(self):
        """Test case for system_access_authentication_get

        Retrieve the reader's authentication configuration.  # noqa: E501
        """
        pass

    def test_system_access_authentication_put(self):
        """Test case for system_access_authentication_put

        Update the reader's authentication configuration.  # noqa: E501
        """
        pass

    def test_system_access_users_get(self):
        """Test case for system_access_users_get

        Retrieve the list of users.  # noqa: E501
        """
        pass

    def test_system_access_users_user_id_password_put(self):
        """Test case for system_access_users_user_id_password_put

        Update the password for the specified user.  # noqa: E501
        """
        pass

    def test_system_antenna_hub_disable_post(self):
        """Test case for system_antenna_hub_disable_post

        Disable the antenna-hub feature.  # noqa: E501
        """
        pass

    def test_system_antenna_hub_enable_post(self):
        """Test case for system_antenna_hub_enable_post

        Enable the antenna-hub feature.  # noqa: E501
        """
        pass

    def test_system_antenna_hub_get(self):
        """Test case for system_antenna_hub_get

        Retrieve antenna-hub information.  # noqa: E501
        """
        pass

    def test_system_cap_installation_get(self):
        """Test case for system_cap_installation_get

        Retrieve the current installation configuration settings.  # noqa: E501
        """
        pass

    def test_system_cap_installation_put(self):
        """Test case for system_cap_installation_put

        Update CAP installation configuration settings.  # noqa: E501
        """
        pass

    def test_system_certificates_ca_certs_cert_id_delete(self):
        """Test case for system_certificates_ca_certs_cert_id_delete

        Remove CA certificate.  # noqa: E501
        """
        pass

    def test_system_certificates_ca_certs_cert_id_get(self):
        """Test case for system_certificates_ca_certs_cert_id_get

        Retrieve CA certificate.  # noqa: E501
        """
        pass

    def test_system_certificates_ca_certs_get(self):
        """Test case for system_certificates_ca_certs_get

        Retrieve CA certificates.  # noqa: E501
        """
        pass

    def test_system_certificates_ca_certs_post(self):
        """Test case for system_certificates_ca_certs_post

        Install CA certificates.  # noqa: E501
        """
        pass

    def test_system_certificates_cap_certs_cert_id_delete(self):
        """Test case for system_certificates_cap_certs_cert_id_delete

        Remove CAP authentication certificate.  # noqa: E501
        """
        pass

    def test_system_certificates_cap_certs_cert_id_get(self):
        """Test case for system_certificates_cap_certs_cert_id_get

        Retrieve a CAP authentication certificate.  # noqa: E501
        """
        pass

    def test_system_certificates_cap_certs_get(self):
        """Test case for system_certificates_cap_certs_get

        Retrieve CAP authentication certificates.  # noqa: E501
        """
        pass

    def test_system_certificates_cap_certs_post(self):
        """Test case for system_certificates_cap_certs_post

        Install CAP authentication certificates.  # noqa: E501
        """
        pass

    def test_system_certificates_tls_certs_cert_id_delete(self):
        """Test case for system_certificates_tls_certs_cert_id_delete

        Remove TLS certificate.  # noqa: E501
        """
        pass

    def test_system_certificates_tls_certs_cert_id_get(self):
        """Test case for system_certificates_tls_certs_cert_id_get

        Retrieve TLS certficate.  # noqa: E501
        """
        pass

    def test_system_certificates_tls_certs_get(self):
        """Test case for system_certificates_tls_certs_get

        Retrieve TLS certificates.  # noqa: E501
        """
        pass

    def test_system_certificates_tls_certs_post(self):
        """Test case for system_certificates_tls_certs_post

        Install TLS certificate.  # noqa: E501
        """
        pass

    def test_system_certificates_tls_csr_post(self):
        """Test case for system_certificates_tls_csr_post

        Create a certificate signing request(CSR).  # noqa: E501
        """
        pass

    def test_system_certificates_tls_services_tls_service_get(self):
        """Test case for system_certificates_tls_services_tls_service_get

        Retrieve certificate info for the specified service.  # noqa: E501
        """
        pass

    def test_system_certificates_tls_services_tls_service_put(self):
        """Test case for system_certificates_tls_services_tls_service_put

        Update certificate info for the specified service.  # noqa: E501
        """
        pass

    def test_system_diagnostics_debug_bundle_get(self):
        """Test case for system_diagnostics_debug_bundle_get

        Generate and retrieve a diagnostic bundle.  # noqa: E501
        """
        pass

    def test_system_diagnostics_watchdog_bundle_delete(self):
        """Test case for system_diagnostics_watchdog_bundle_delete

        Delete core files and diagnostic bundle generated by a watchdog reboot.  # noqa: E501
        """
        pass

    def test_system_diagnostics_watchdog_bundle_get(self):
        """Test case for system_diagnostics_watchdog_bundle_get

        Retrieve diagnostic bundle generated by a watchdog reboot.  # noqa: E501
        """
        pass

    def test_system_get(self):
        """Test case for system_get

        Retrieve details about the reader hardware.  # noqa: E501
        """
        pass

    def test_system_hostname_get(self):
        """Test case for system_hostname_get

        Retrieve the reader hostname.  # noqa: E501
        """
        pass

    def test_system_hostname_put(self):
        """Test case for system_hostname_put

        Update the reader hostname.  # noqa: E501
        """
        pass

    def test_system_http_get(self):
        """Test case for system_http_get

        Retrieve the current HTTP server configuration settings.  # noqa: E501
        """
        pass

    def test_system_http_put(self):
        """Test case for system_http_put

        Update HTTP server configuration settings.  # noqa: E501
        """
        pass

    def test_system_https_get(self):
        """Test case for system_https_get

        Retrieve the current HTTPS server configuration settings.  # noqa: E501
        """
        pass

    def test_system_https_put(self):
        """Test case for system_https_put

        Update HTTPS server configuration settings.  # noqa: E501
        """
        pass

    def test_system_image_get(self):
        """Test case for system_image_get

        Retrieve details about the reader's firmware.  # noqa: E501
        """
        pass

    def test_system_image_upgrade_get(self):
        """Test case for system_image_upgrade_get

        Get details about the state of a firmware upgrade.  # noqa: E501
        """
        pass

    def test_system_image_upgrade_post(self):
        """Test case for system_image_upgrade_post

        Upload an upgrade file for installation.  # noqa: E501
        """
        pass

    def test_system_mdns_get(self):
        """Test case for system_mdns_get

        Retrieve the current mDNS configuration settings.  # noqa: E501
        """
        pass

    def test_system_mdns_put(self):
        """Test case for system_mdns_put

        Update mDNS configuration settings.  # noqa: E501
        """
        pass

    def test_system_network_dns_domains_get(self):
        """Test case for system_network_dns_domains_get

        Retrieve the search domains.  # noqa: E501
        """
        pass

    def test_system_network_dns_domains_put(self):
        """Test case for system_network_dns_domains_put

        Update static search domains used by the reader.  # noqa: E501
        """
        pass

    def test_system_network_dns_servers_get(self):
        """Test case for system_network_dns_servers_get

        Retrieve the DNS servers from the reader.  # noqa: E501
        """
        pass

    def test_system_network_dns_servers_put(self):
        """Test case for system_network_dns_servers_put

        Update the static DNS servers used by the reader.  # noqa: E501
        """
        pass

    def test_system_network_interfaces_get(self):
        """Test case for system_network_interfaces_get

        Retrieve the current network information for all interfaces.  # noqa: E501
        """
        pass

    def test_system_network_interfaces_interface_id_get(self):
        """Test case for system_network_interfaces_interface_id_get

        Retrieve the specified network interface state.  # noqa: E501
        """
        pass

    def test_system_network_interfaces_interface_id_network_protocol_configuration_get(self):
        """Test case for system_network_interfaces_interface_id_network_protocol_configuration_get

        Retrieve the current configuration of a network interface.  # noqa: E501
        """
        pass

    def test_system_network_interfaces_interface_id_network_protocol_configuration_put(self):
        """Test case for system_network_interfaces_interface_id_network_protocol_configuration_put

        Update the IP configuration of a network interface.  # noqa: E501
        """
        pass

    def test_system_network_interfaces_interface_id_put(self):
        """Test case for system_network_interfaces_interface_id_put

        Enable the specified network interface.  # noqa: E501
        """
        pass

    def test_system_network_interfaces_interface_id_wlan_access_points_get(self):
        """Test case for system_network_interfaces_interface_id_wlan_access_points_get

        Retrieve a list of the available access points using the specified network interface.  # noqa: E501
        """
        pass

    def test_system_network_interfaces_interface_id_wlan_connection_get(self):
        """Test case for system_network_interfaces_interface_id_wlan_connection_get

        Retrieve the current WLAN connection status.  # noqa: E501
        """
        pass

    def test_system_network_interfaces_interface_id_wlan_connection_put(self):
        """Test case for system_network_interfaces_interface_id_wlan_connection_put

        Request a connection to the specified access point.  # noqa: E501
        """
        pass

    def test_system_power_get(self):
        """Test case for system_power_get

        Retrieve the current power configuration.  # noqa: E501
        """
        pass

    def test_system_power_put(self):
        """Test case for system_power_put

        Configure the power source.  # noqa: E501
        """
        pass

    def test_system_reboot_post(self):
        """Test case for system_reboot_post

        Reboot the system.  # noqa: E501
        """
        pass

    def test_system_region_get(self):
        """Test case for system_region_get

        Retrieve region information.  # noqa: E501
        """
        pass

    def test_system_region_put(self):
        """Test case for system_region_put

        Configure the operating region.  # noqa: E501
        """
        pass

    def test_system_rfid_interface_get(self):
        """Test case for system_rfid_interface_get

        Retrieve the reader API.  # noqa: E501
        """
        pass

    def test_system_rfid_interface_put(self):
        """Test case for system_rfid_interface_put

        Configure the reader API.  # noqa: E501
        """
        pass

    def test_system_rfid_llrp_get(self):
        """Test case for system_rfid_llrp_get

        Retrieve LLRP status.  # noqa: E501
        """
        pass

    def test_system_time_get(self):
        """Test case for system_time_get

        Retrieve information about system time and uptime.  # noqa: E501
        """
        pass

    def test_system_time_ntp_get(self):
        """Test case for system_time_ntp_get

        Retrieve the current state of the NTP service.  # noqa: E501
        """
        pass

    def test_system_time_ntp_put(self):
        """Test case for system_time_ntp_put

        Configure the NTP service.  # noqa: E501
        """
        pass

    def test_system_time_ntp_servers_get(self):
        """Test case for system_time_ntp_servers_get

        Retrieve NTP servers.  # noqa: E501
        """
        pass

    def test_system_time_ntp_servers_post(self):
        """Test case for system_time_ntp_servers_post

        Add a static NTP server.  # noqa: E501
        """
        pass

    def test_system_time_ntp_servers_server_id_delete(self):
        """Test case for system_time_ntp_servers_server_id_delete

        Remove a static NTP server.  # noqa: E501
        """
        pass

    def test_system_time_ntp_servers_server_id_get(self):
        """Test case for system_time_ntp_servers_server_id_get

        Retrieve details on a specific NTP server.  # noqa: E501
        """
        pass

    def test_system_time_put(self):
        """Test case for system_time_put

        Update the system time.  # noqa: E501
        """
        pass

    def test_webhooks_event_get(self):
        """Test case for webhooks_event_get

        Get the event webhook configuration.  # noqa: E501
        """
        pass

    def test_webhooks_event_put(self):
        """Test case for webhooks_event_put

        Set the event webhook configuration.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
