# coding: utf-8

"""
    Impinj Reader Configuration REST API

    This API provides an interface for configuring RFID operations and reporting streams on Impinj Readers as well as updating Impinj Reader firmware and configuring system settings.  When retrieved from a reader, this OpenAPI Document is dynamically updated based on the capabilities of the reader. See the '/openapi.json' path.   # noqa: E501

    OpenAPI spec version: 1.7.0
    Contact: developer-feedback@impinj.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class GpoConfiguration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gpo': 'int',
        'state': 'str'
    }

    attribute_map = {
        'gpo': 'gpo',
        'state': 'state'
    }

    def __init__(self, gpo=None, state=None, _configuration=None):  # noqa: E501
        """GpoConfiguration - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._gpo = None
        self._state = None
        self.discriminator = None

        self.gpo = gpo
        self.state = state

    @property
    def gpo(self):
        """Gets the gpo of this GpoConfiguration.  # noqa: E501

        The GPO pin number.  # noqa: E501

        :return: The gpo of this GpoConfiguration.  # noqa: E501
        :rtype: int
        """
        return self._gpo

    @gpo.setter
    def gpo(self, gpo):
        """Sets the gpo of this GpoConfiguration.

        The GPO pin number.  # noqa: E501

        :param gpo: The gpo of this GpoConfiguration.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and gpo is None:
            raise ValueError("Invalid value for `gpo`, must not be `None`")  # noqa: E501

        self._gpo = gpo

    @property
    def state(self):
        """Gets the state of this GpoConfiguration.  # noqa: E501

        The current the state of the pin.  # noqa: E501

        :return: The state of this GpoConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this GpoConfiguration.

        The current the state of the pin.  # noqa: E501

        :param state: The state of this GpoConfiguration.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501
        allowed_values = ["low", "high"]  # noqa: E501
        if (self._configuration.client_side_validation and
                state not in allowed_values):
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GpoConfiguration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GpoConfiguration):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GpoConfiguration):
            return True

        return self.to_dict() != other.to_dict()
