# coding: utf-8

"""
    Impinj Reader Configuration REST API

    This API provides an interface for configuring RFID operations and reporting streams on Impinj Readers as well as updating Impinj Reader firmware and configuring system settings.  When retrieved from a reader, this OpenAPI Document is dynamically updated based on the capabilities of the reader. See the '/openapi.json' path.   # noqa: E501

    OpenAPI spec version: 1.7.0
    Contact: developer-feedback@impinj.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class NetworkWlanConnection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ssid': 'str',
        'password': 'str'
    }

    attribute_map = {
        'ssid': 'ssid',
        'password': 'password'
    }

    def __init__(self, ssid=None, password=None, _configuration=None):  # noqa: E501
        """NetworkWlanConnection - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._ssid = None
        self._password = None
        self.discriminator = None

        self.ssid = ssid
        self.password = password

    @property
    def ssid(self):
        """Gets the ssid of this NetworkWlanConnection.  # noqa: E501

        A SSID (Service Set IDentifier) is the access point name.  # noqa: E501

        :return: The ssid of this NetworkWlanConnection.  # noqa: E501
        :rtype: str
        """
        return self._ssid

    @ssid.setter
    def ssid(self, ssid):
        """Sets the ssid of this NetworkWlanConnection.

        A SSID (Service Set IDentifier) is the access point name.  # noqa: E501

        :param ssid: The ssid of this NetworkWlanConnection.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and ssid is None:
            raise ValueError("Invalid value for `ssid`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                ssid is not None and len(ssid) > 32):
            raise ValueError("Invalid value for `ssid`, length must be less than or equal to `32`")  # noqa: E501
        if (self._configuration.client_side_validation and
                ssid is not None and len(ssid) < 1):
            raise ValueError("Invalid value for `ssid`, length must be greater than or equal to `1`")  # noqa: E501

        self._ssid = ssid

    @property
    def password(self):
        """Gets the password of this NetworkWlanConnection.  # noqa: E501

        Access point password.  # noqa: E501

        :return: The password of this NetworkWlanConnection.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this NetworkWlanConnection.

        Access point password.  # noqa: E501

        :param password: The password of this NetworkWlanConnection.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                password is not None and len(password) > 63):
            raise ValueError("Invalid value for `password`, length must be less than or equal to `63`")  # noqa: E501
        if (self._configuration.client_side_validation and
                password is not None and len(password) < 8):
            raise ValueError("Invalid value for `password`, length must be greater than or equal to `8`")  # noqa: E501

        self._password = password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NetworkWlanConnection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NetworkWlanConnection):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NetworkWlanConnection):
            return True

        return self.to_dict() != other.to_dict()
