# coding: utf-8

"""
    Impinj Reader Configuration REST API

    This API provides an interface for configuring RFID operations and reporting streams on Impinj Readers as well as updating Impinj Reader firmware and configuring system settings.  When retrieved from a reader, this OpenAPI Document is dynamically updated based on the capabilities of the reader. See the '/openapi.json' path.   # noqa: E501

    OpenAPI spec version: 1.7.0
    Contact: developer-feedback@impinj.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class SearchDomains(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'static_search_domains': 'list[SearchDomain]',
        'dynamic_search_domains': 'list[SearchDomain]'
    }

    attribute_map = {
        'static_search_domains': 'staticSearchDomains',
        'dynamic_search_domains': 'dynamicSearchDomains'
    }

    def __init__(self, static_search_domains=None, dynamic_search_domains=None, _configuration=None):  # noqa: E501
        """SearchDomains - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._static_search_domains = None
        self._dynamic_search_domains = None
        self.discriminator = None

        self.static_search_domains = static_search_domains
        if dynamic_search_domains is not None:
            self.dynamic_search_domains = dynamic_search_domains

    @property
    def static_search_domains(self):
        """Gets the static_search_domains of this SearchDomains.  # noqa: E501


        :return: The static_search_domains of this SearchDomains.  # noqa: E501
        :rtype: list[SearchDomain]
        """
        return self._static_search_domains

    @static_search_domains.setter
    def static_search_domains(self, static_search_domains):
        """Sets the static_search_domains of this SearchDomains.


        :param static_search_domains: The static_search_domains of this SearchDomains.  # noqa: E501
        :type: list[SearchDomain]
        """
        if self._configuration.client_side_validation and static_search_domains is None:
            raise ValueError("Invalid value for `static_search_domains`, must not be `None`")  # noqa: E501

        self._static_search_domains = static_search_domains

    @property
    def dynamic_search_domains(self):
        """Gets the dynamic_search_domains of this SearchDomains.  # noqa: E501


        :return: The dynamic_search_domains of this SearchDomains.  # noqa: E501
        :rtype: list[SearchDomain]
        """
        return self._dynamic_search_domains

    @dynamic_search_domains.setter
    def dynamic_search_domains(self, dynamic_search_domains):
        """Sets the dynamic_search_domains of this SearchDomains.


        :param dynamic_search_domains: The dynamic_search_domains of this SearchDomains.  # noqa: E501
        :type: list[SearchDomain]
        """

        self._dynamic_search_domains = dynamic_search_domains

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchDomains, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchDomains):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SearchDomains):
            return True

        return self.to_dict() != other.to_dict()
